[package]
name = "fanim"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "bleed"

[[bin]]
name = "snow"

[[bin]]
name = "pickover"

[dependencies]
bevy_app = "0.18.0"
bevy_derive = "0.18.0"
bevy_ecs = "0.18.0"
colorgrad = { version = "0.8.0", features = ["preset"] }
env_logger = "0.11.8"
png = { version = "0.18.0", features = ["zlib-rs"] }
pollster = "0.4.0"
rustfft = "6.4.1"
symphonium = { version = "0.7.1", features = ["resampler", "mp3"] }
tint = { path = "tint", features = ["std", "serde"] }
wgpu = "28.0.0"
